accounts/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    # path('chef_service/', views.chef_service, name='chef_service'),
    # path('chef_depart/', views.chef_depart, name='chef_depart'),
    # path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path('sg/', views.sg, name='sg'),
    # path('usager/', views.usager, name='usager'),
]

courrier/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('senat.urls')),
    path('univ/', include('univ.urls')),
    path("", index),
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senat/urls.py
from django.urls import path
from . import views
from .views import *
# from .views import SearchResultsView
# from .views import SearchResultsList

app_name = "senat"

urlpatterns = [
    path('chef_service/', views.chef_service, name='chef_service'),
    path('chef_depart/', views.chef_depart, name='chef_depart'),
    path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path(r'^(?P<id>\d+)bureau_sg/$', views.bureau_sg, name='bureau_sg'),
    path('bureau_sg/', views.bureau_sg, name='bureau_sg'),
    # path('bureau_univ/', views.bureau_univ, name='bureau_univ'),
    path('usager/', views.usager, name='usager'),
    path('search/', views.search, name='search'),
    # path('search_univ/', views.search_univ, name='search_univ'),
    path('courrier_attente/', views.courrier_attente, name='courrier_attente'),

    

    path('<int:id>', views.courrier_attente_detail, name='courrier_attente_detail'),
    path('search_chef/', views.search_chef, name='search_chef'),
    path('result_chef/', views.result_chef, name='result_chef'),
    path('/', views.list_courrier, name='list_courrier'),
    path('df/<int:pk>/', views.courrier_pdf, name="courrier_pdf"),
    # path('traited/', views.traited, name='traited'),
    # path("search/", SearchResultsList.as_view(), name="search"),
    # path("search/", SearchResultsView.as_view(), name="search_results"),
    # path('sg_record/', sg_record, name='sg_record'),
    path('envoi_email/', views.envoi_email, name='envoi_email'),

    path('scan', views.scan, name='scan'),




    path('<int:id>', views.deactivate_record, name='deactivate_record'),






    # path('inde/', views.indexs, name='indexs'),
    # path('capture/', views.capture, name='capture'),
    path('captures/', views.captures, name='captures'),
    path('capture/<int:capture_id>/download/', views.download_capture, name='download_capture'),
    path('capture_pdf/<int:capture_id>/download/', views.download_capture_pdf, name='download_capture_pdf'),





    path('search_usager/', views.search_usager, name='search_usager'),
    path('result_usager/', views.result_usager, name='result_usager'),
]

univ/urls.py
from django.urls import path
from . import views
from .views import *
# from .views import SearchResultsView
# from .views import SearchResultsList

app_name = "univ"

urlpatterns = [
    path('chef_univ/', views.chef_univ, name='chef_univ'),
    # path('chef_depart/', views.chef_depart, name='chef_depart'),
    # path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path(r'^(?P<id>\d+)bureau_sg/$', views.bureau_sg, name='bureau_sg'),
    # path('bureau_sg/', views.bureau_sg, name='bureau_sg'),
    path('bureau_univ/', views.bureau_univ, name='bureau_univ'),
    # path('usager/', views.usager, name='usager'),
    # path('search/', views.search, name='search'),
    path('search_univ/', views.search_univ, name='search_univ'),
    path('courrier_attente/', views.courrier_attente, name='courrier_attente'),

    

    path('<int:id>', views.courrier_attente_detail, name='courrier_attente_detail'),
    path('search_chef/', views.search_chef, name='search_chef'),
    path('result_chef/', views.result_chef, name='result_chef'),
    path('/', views.list_courrier, name='list_courrier'),
    path('df/<int:pk>/', views.courrier_pdf, name="courrier_pdf"),
    # path('traited/', views.traited, name='traited'),
    # path("search/", SearchResultsList.as_view(), name="search"),
    # path("search/", SearchResultsView.as_view(), name="search_results"),
    # path('sg_record/', sg_record, name='sg_record'),
    path('envoi_email/', views.envoi_email, name='envoi_email'),

    path('scan', views.scan, name='scan'),




    path('<int:id>', views.deactivate_record, name='deactivate_record'),






    # path('inde/', views.indexs, name='indexs'),
    # path('capture/', views.capture, name='capture'),
    path('captures/', views.captures, name='captures'),
    path('capture/<int:capture_id>/download/', views.download_capture, name='download_capture'),
    path('capture_pdf/<int:capture_id>/download/', views.download_capture_pdf, name='download_capture_pdf'),




    path('search_usager/', views.search_usager, name='search_usager'),
    path('result_usager/', views.result_usager, name='result_usager'),
]

senat/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from senat.forms import *
from datetime import datetime
import random
from .models import Courrier
from django.views import View
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
import json
from django.db.models import Q # new
from django.views.generic import ListView
from django.urls import reverse
import pdfkit
from django.http import HttpResponse
from django.template import loader
import io
from .utils import render_to_pdf
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .filters import CourrierFilter
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView







from django.forms import modelform_factory
# from .models import Picture

from django.core.files.storage import FileSystemStorage
# from .models import WebcamImage
from django.core.files.base import ContentFile
from django.utils import timezone
import re
from django.http import HttpResponseBadRequest




def chef_service(request):

    courrier = Courrier.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    form = RegistrationForm(request.POST or None)
    chef_service = Courrier()

    if request.method == 'POST':
        # if code_unique:
        #     form = CiviliteForm(request.POST or None, instance=etudiant)
        #     if form.is_valid():
        #         form.save()
        #         messages.add_message(request, messages.SUCCESS, _(f"Informations de civilité modifiées avec succès."))
        #         return redirect('logement:filiation')
        #     else:
        #         messages.add_message(request, messages.ERROR, _('Veuillez vérifier les champs en rouge !!!'))
        #         return render(request, 'logement/civilite.html', {'form': form})
        # else:
        #     form = CiviliteForm(request.POST or None)
        #     etudiant = DemandeChambre()

        # form = RegistrationForm(request.POST or None)
        # chef_service = Courrier()

        if form.is_valid():
            # code_unique = generate_unique_code(str(form.cleaned_data['date_nais']))

            # etudiant.num_ordre = code_unique

            chef_service.transmetteur = form.cleaned_data['transmetteur']                
            chef_service.recepteur = form.cleaned_data['recepteur']                
            chef_service.code = form.cleaned_data['code']                
            chef_service.date = form.cleaned_data['date']                
            chef_service.objet = form.cleaned_data['objet']
            chef_service.structure = form.cleaned_data['structure']                
            chef_service.annee = form.cleaned_data['annee']
            chef_service.types = form.cleaned_data['types']
        
            chef_service.save()
            # request.session['code_logement'] = code_unique

            messages.add_message(request, messages.SUCCESS, (f"Informations du courrier enregistrées avec succès."))
            # return redirect('logement:filiation', request.session['ecole_code'] )
            return redirect('senat:chef_service')
        else:
            messages.add_message(request, messages.ERROR, ('Veuillez vérifier les champs en rouge !!!'))
            return render(request, 'chef_service.html', {'form': form})

    context = {
        'form': form,
        'count_courrier': count_courrier,
    }
    return render(request,'chef_service.html', context)



def chef_depart(request):
    return render(request,'chef_depart.html')



def chef_arrive(request):
    return render(request,'chef_arrive.html')



def bureau_sg(request):
    type_elt = request.GET.get('types')
    code = request.GET.get('code')

    # courrier = Courrier.objects.filter(
    #     Q(code__icontains=code) and Q(types__icontains=type_elt)
    # )
    courrier = Courrier.objects.filter(
        code=code, types=type_elt
    )
    # courriers = Courrier.objects.raw('select * from courrier where code="'+code+'" and types="'+type_elt+'"') 
    # if len(courriers) > 0:
    #     courrier = courriers.first()

    # sg = get_object_or_404(Courrier)
    # form = MentionForm(instance=sg)
    
    
    sg = get_object_or_404(Courrier, code=code, types=type_elt)
    form = MentionForm(instance=sg)

    # courrierss = MentionForm(request.POST or None, instance=code)
    if request.method == 'POST':
        form = MentionForm(request.POST or None, instance=sg)
        if form.is_valid():
            sg.service_traitement = form.cleaned_data['service_traitement']
            sg.mention = form.cleaned_data['mention']                
            # sg.service_traitement = form.cleaned_data['service_traitement'] 
            sg.save()
            messages.add_message(request, messages.SUCCESS, (f"Informations du courrier enregistrées avec succès."))
            # return redirect('senat:bureau_sg')

    return render(request,'sg.html', {"courrier": courrier, "form": form})



def usager(request):
    return render(request,'usager.html')



def search(request):
    
#     # clear_session(request)

#     # context = {}

#     # if request.method == 'POST':
#     #     code = request.POST['code']

#     #     if isinstance(code, str):
#     #         return redirect('senat:sg', code)
#     #     else:
#     #         messages.add_message(request, messages.ERROR, ('Mauvais format de code !!!'))
#     #         return render(request, 'search.html', {'code': code})

#     # return render(request, 'search.html', context)

#     # if request.method == 'GET':
#     #     query = request.GET.get('code')
#     #     if query:
#     #         courrier = Courrier.objects.filter(code__icontains=query) 
#     #         return render(request, 'sg.html', {'courrier':courrier})
#     #     else:
#     #         # messages.add_message(request, messages.ERROR, ('Mauvais format de code !!!'))
#     #         return render(request, 'search.html', {})

#     # if request.method == 'GET':
#     #     query = request.GET.get('code')
#     #     querys = request.GET.get('types')
#     #     if query:
#     #         courrier = Courrier.objects.raw('select * from courrier where code="'+query+'" and types="'+querys+'"') 
#     #         return render(request, 'sg.html', {'courrier':courrier})
#     #     else:
#     #         # messages.add_message(request, messages.ERROR, ('Mauvais format de code !!!'))
#     #         return render(request, 'search.html', {})

    if request.method == 'POST':
        query = request.POST.get('code')
        querys = request.POST.get('types')
        # courrier = Courrier.objects.raw('select * from courrier where code="'+query+'" and types="'+querys+'"') 


        # if not query or not querys:
        #     messages.error(request, 'Vous devez renseigner ls champs.')
        # return redirect('senat:search')

        objects = Courrier.objects.filter(code=query, types=querys, structure="SENAT")
        if not objects: 
            messages.error(request, "Le code ou le type fourni n'existe pas")
            return redirect('senat:search')


        response = redirect('/bureau_sg/' + f'?code={query}&types={querys}')
        # messages.add_message(request, messages.ERROR, ('Mauvais format de code !!!'))
        return response

        # return redirect('senat:bureau_sg', kwargs={'courrier':courrier})
        # return render(request, 'sg.html', {'courrier':courrier})
        # return redirect(f'senat:bureau_sg/?query={query}/?querys={querys}')
        # return redirect('senat:bureau_sg')
    else:
        # messages.add_message(request, messages.ERROR, ('Mauvais format de code !!!'))
        return render(request, 'search.html')



# def bureau_univ(request):
#     type_elt = request.GET.get('types')
#     code = request.GET.get('code')
#     courrier = Courrier.objects.filter(
#         code=code, types=type_elt
#     )
#     sg = get_object_or_404(Courrier, code=code, types=type_elt)
#     form = MentionForm(instance=sg)

#     if request.method == 'POST':
#         form = MentionForm(request.POST or None, instance=sg)
#         if form.is_valid():
#             sg.service_traitement = form.cleaned_data['service_traitement']
#             sg.mention = form.cleaned_data['mention']                
            
#             sg.save()
#             messages.add_message(request, messages.SUCCESS, (f"Informations du courrier enregistrées avec succès."))

#     return render(request,'univ.html', {"courrier": courrier, "form": form})


# def search_univ(request):

#     if request.method == 'POST':
#         query = request.POST.get('code')
#         querys = request.POST.get('types')
        

#         objects = Courrier.objects.filter(code=query, types=querys, structure="UNIVERSITE DE YAOUNDE 1")
#         if not objects: 
#             messages.error(request, "Le code ou le type fourni n'existe pas")
#             return redirect('senat:search_univ')
#         response = redirect('/bureau_univ/' + f'?code={query}&types={querys}')
#         return response
#     else:
#         return render(request, 'search_univ.html')



def courrier_attente(request):
    courrier = Courrier.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    # if request.method == 'POST':
    #     request.is_active = False
    #     request.save()
    #compter le nombre de courrier
    courrier = Courrier.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    return render(request, 'courrier_attente.html', {"courrier": courrier, "count_courrier": count_courrier})



def deactivate_record(request, id):
    record = get_object_or_404(Courrier, pk=id)
    if request.method == 'POST':

senat/templates/courrier_attente.html
{% load static %}
{% load crispy_forms_tags %}





<!DOCTYPE html>
<html>
<head>
  <title> Enregistrement du courrier - Chef service du courrier </title>
<meta charset="UTF-8">
<!-- This script got from frontendfreecode.com -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="icon" type="image/x-icon" href="{% static 'landing/assets/img/favicon.png' %}">
<script src=“https://code.jquery.com/jquery-3.5.1.min.js” integrity=“sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj” crossorigin=“anonymous”></script>

<style>
    @import url('https://fonts.googleapis.com/css?family=Muli&display=swap');
    @import url('https://fonts.googleapis.com/css?family=Quicksand&display=swap');
body {
    font-family: 'Quicksand', sans-serif;
    /*font-size: 14px;
    line-height: 1.8;
    font-weight: normal;
    background: #fafafa;*/
  
}
.wrapper {
    display: flex;
    width: 100%;
}

.img {
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
}

#sidebar {
    height: 100%;
    width: 300px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #2a5555; 
    overflow-x: hidden;
    transition: all 0.3s;
}

#sidebar .sidebar-header {
    padding: 20px;
    /*background-color: #2a5555;*/
    color: #fff;
}

#sidebar ul.components {
    padding: 20px 0;
    /*border-bottom: 1px solid #47748b;*/
}

#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    padding-left: 20px;
    font-size: 1.1em;
    display: block;
    color: #fff;
    text-decoration: none;
}

#sidebar ul li a:hover {
    text-decoration: none;
    background-color: #0B7474;
}

#sidebarCollapse {
    display: none;
}

#content {
    width: 100%;
    padding-left: 350px;
    transition: all 0.3s;
}
/*#content {
    width: 100%;
    padding: 0;
    min-height: 100vh;
    -webkit-transition: all 0.3s;
    -o-transition: all 0.3s;
    transition: all 0.3s;
}*/
.active{
    background-color: #0B7474;
}


/*--------------------------------------------------------------
# Sections General
--------------------------------------------------------------*/
.section-title {
    margin-top: 30px;
    text-align: center;
    padding: 30px 0;
    position: relative;
  }
  
  .section-title h2 {
    font-size: 32px;
    font-weight: 700;
    text-transform: uppercase;
    margin-bottom: 20px;
    padding-bottom: 0;
    color: #191919;
    position: relative;
    z-index: 2;
  }
  
  .section-title span {
    position: absolute;
    top: 30px;
    color: #f4f4f4;
    left: 0;
    right: 0;
    z-index: 1;
    font-weight: 700;
    font-size: 52px;
    text-transform: uppercase;
    line-height: 0;
  }
  
  .section-title p {
    margin-bottom: 0;
    position: relative;
    z-index: 2;
  }
  
  @media (max-width: 575px) {
    .section-title h2 {
      font-size: 28px;
      margin-bottom: 15px;
    }
  
    .section-title span {
      font-size: 38px;
    }
  }
</style>

</head>
<body>


    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header text-center">
                {% comment %} <h5>Cybex Courrier</h5> {% endcomment %}
                <img src="{% static 'landing/assets/img/cybex-logo.png' %}" class="" style="width: 250px;">
            </div>
            {% comment %} <a href="#" class="img logo rounded-circle mb-3" style="background-image: url(http://frontendfreecode.com/img/user.jpg);"></a> {% endcomment %}
            <div class="text-center">
                <img src="{% static 'landing/assets/img/about.jpg' %}" class="img logo rounded-circle mb-3 mt-2" style="width: 100px; height: 100px;">
            </div>
            <p class="text-center" style="color: #fff"><span style="font-size: 20px; color: #fff">{{ user.username | upper }}</span> <br> Chef du Service Courrier</p>
            <ul class="list-unstyled components">
                <li>
                    <a href="{% url 'account:index' %}">
                        <i class="ri-logout-circle-line"></i>
                        Deconnexion
                    </a>
                </li>
                <li>
                    <a href="{% url 'senat:chef_service' %}">
                        <i class="fas fa-user mr-2"></i>
                        Enregistrer un Courrier
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'senat:courrier_attente' %}">
                        <i class="fas fa-user mr-2"></i>
                        Courrier en attente <span style="font-size:10px; border: 1px solid red; padding-left: 3px; padding-right: 3px; border-radius: %; background-color: red">{{ count_courrier }}</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'senat:search_chef' %}">
                        <i class="fas fa-tasks mr-2"></i>
                        Recherche d'un Courrier
                    </a>
                </li>
                <li>
                    <a href="{% url 'senat:list_courrier' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Listing des Courriers
                    </a>
                </li>
                <li>
                    <a href="{% url 'senat:envoi_email' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Email
                    </a>
                </li>
                <li>
                    <a href="{% url 'senat:scan' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Scanner un Courrier
                    </a>
                </li>
                <li>
                    <a href="{% url 'senat:captures' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Imprimer un Courrier
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Page Content -->
        <div id="content" >
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                </div>
            </nav>

            <div class="container-fluid">
                {% comment %} <h2 class="mb-4 mt-4">LISTE DE COURRIERS EN ATTENTE</h2> {% endcomment %}
                <div class="section-title">
                    <span>LISTE DE COURRIERS EN ATTENTE</span>
                    <h2>LISTE DE COURRIERS EN ATTENTE</h2>
                </div>
                <div class="container">
                    <div class="row">
                        {% for courriers in courrier %}
                            <div class="col-12 col-sm-6 col-lg-4 mb-4">
                                <div class="card" style="border-color:; box-shadow: 0px 10px 15px -3px rgba(0,0,0,0.1);">
                                    <div class="card-body" style="border-top: 5px solid #2a5555; border-radius: 3px;">
                                        <p style="font-size: 20px; font-weight: bold;">
                                            Code: {{ courriers.code }}
                                        <p>
                                        <a style="color: black" href=" {% url 'senat:courrier_attente_detail' courriers.id %} ">
                                            <button type="button" class="btn btn-primary" style="background-color: green; border: none">Détail</button>
                                        </a>
                                        {% comment %} {% for records in record %} {% endcomment %}
                                            {% comment %} <form method=“post” action="{% url 'senat:deactivate_record' courriers.pk %}"> {% endcomment %}
                                                <button type="button" class="btn btn-primary" style="background-color: red; border: none" data-toggle="modal" data-target="#exampleModal">Terminer</button>
                                            {% comment %} </form> {% endcomment %}
                                        {% comment %} {% endfor %} {% endcomment %}
                                        {% comment %} <form method="POST">
                                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">COURRIER</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                    </div>
                                                    <div class="modal-body">
                                                    En cliquant sur OUI vous confirmez avoir traité le courrier
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" style="background-color: red; border: none" class="btn btn-secondary" data-dismiss="modal">NON</button>
                                                        {% if record.is_active %}
                                                            <button type="button" data-record-id="{{ record.pk }}" id="deactivatePersonBtn" style="background-color: green; border: none" class="btn btn-primary deactivate-btn" >OUI</button>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                                </div>
                                            </div>
                                        </form> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>







{% comment %} 
<script>
    (document).ready(function() {
        ('.record-link').click(function(e) {
            e.preventDefault();
            var url = (this).attr('href');

            .get(url, function(data) {
                ('#modal-content').html(data);
                ('#record-detail-modal').modal('show');
            });
        });

        ('.deactivate-btn').click(function() {
            (this).data('record-id');
            var url = '{% url 'senat:deactivate_record' pk=' + recordId + ' %}';

            $.post(url, function(data) {
                if (data.url) {
                    window.location.href = data.url;
                }
            });
        });
    });
</script> {% endcomment %}

</body>
</html>