accounts/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    # path('chef_service/', views.chef_service, name='chef_service'),
    # path('chef_depart/', views.chef_depart, name='chef_depart'),
    # path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path('sg/', views.sg, name='sg'),
    # path('usager/', views.usager, name='usager'),
]

courrier/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('senat.urls')),
    path('univ/', include('univ.urls')),
    path("", index),
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senat/urls.py
from django.urls import path
from . import views
from .views import *
# from .views import SearchResultsView
# from .views import SearchResultsList

app_name = "senat"

urlpatterns = [
    path('chef_service/', views.chef_service, name='chef_service'),
    path('chef_depart/', views.chef_depart, name='chef_depart'),
    path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path(r'^(?P<id>\d+)bureau_sg/$', views.bureau_sg, name='bureau_sg'),
    path('bureau_sg/', views.bureau_sg, name='bureau_sg'),
    # path('bureau_univ/', views.bureau_univ, name='bureau_univ'),
    path('usager/', views.usager, name='usager'),
    path('search/', views.search, name='search'),
    # path('search_univ/', views.search_univ, name='search_univ'),
    path('courrier_attente/', views.courrier_attente, name='courrier_attente'),

    

    path('<int:id>', views.courrier_attente_detail, name='courrier_attente_detail'),
    path('search_chef/', views.search_chef, name='search_chef'),
    path('result_chef/', views.result_chef, name='result_chef'),
    path('/', views.list_courrier, name='list_courrier'),
    path('df/<int:pk>/', views.courrier_pdf, name="courrier_pdf"),
    # path('traited/', views.traited, name='traited'),
    # path("search/", SearchResultsList.as_view(), name="search"),
    # path("search/", SearchResultsView.as_view(), name="search_results"),
    # path('sg_record/', sg_record, name='sg_record'),
    path('envoi_email/', views.envoi_email, name='envoi_email'),

    path('scan', views.scan, name='scan'),




    path('<int:id>', views.deactivate_record, name='deactivate_record'),






    # path('inde/', views.indexs, name='indexs'),
    # path('capture/', views.capture, name='capture'),
    path('captures/', views.captures, name='captures'),
    path('capture/<int:capture_id>/download/', views.download_capture, name='download_capture'),
    path('capture_pdf/<int:capture_id>/download/', views.download_capture_pdf, name='download_capture_pdf'),





    path('search_usager/', views.search_usager, name='search_usager'),
    path('result_usager/', views.result_usager, name='result_usager'),
]

univ/urls.py
from django.urls import path
from . import views
from .views import *
# from .views import SearchResultsView
# from .views import SearchResultsList

app_name = "univ"

urlpatterns = [
    path('chef_univ/', views.chef_univ, name='chef_univ'),
    # path('chef_depart/', views.chef_depart, name='chef_depart'),
    # path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path(r'^(?P<id>\d+)bureau_sg/$', views.bureau_sg, name='bureau_sg'),
    # path('bureau_sg/', views.bureau_sg, name='bureau_sg'),
    path('bureau_univ/', views.bureau_univ, name='bureau_univ'),
    # path('usager/', views.usager, name='usager'),
    # path('search/', views.search, name='search'),
    path('search_univ/', views.search_univ, name='search_univ'),
    path('courrier_attente/', views.courrier_attente, name='courrier_attente'),

    

    path('<int:id>', views.courrier_attente_detail, name='courrier_attente_detail'),
    path('search_chef/', views.search_chef, name='search_chef'),
    path('result_chef/', views.result_chef, name='result_chef'),
    path('/', views.list_courrier, name='list_courrier'),
    path('df/<int:pk>/', views.courrier_pdf, name="courrier_pdf"),
    # path('traited/', views.traited, name='traited'),
    # path("search/", SearchResultsList.as_view(), name="search"),
    # path("search/", SearchResultsView.as_view(), name="search_results"),
    # path('sg_record/', sg_record, name='sg_record'),
    path('envoi_email/', views.envoi_email, name='envoi_email'),

    path('scan', views.scan, name='scan'),




    path('<int:id>', views.deactivate_record, name='deactivate_record'),






    # path('inde/', views.indexs, name='indexs'),
    # path('capture/', views.capture, name='capture'),
    path('captures/', views.captures, name='captures'),
    path('capture/<int:capture_id>/download/', views.download_capture, name='download_capture'),
    path('capture_pdf/<int:capture_id>/download/', views.download_capture_pdf, name='download_capture_pdf'),




    path('search_usager/', views.search_usager, name='search_usager'),
    path('result_usager/', views.result_usager, name='result_usager'),
]

univ/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from univ.forms import *
from datetime import datetime
import random
from .models import Courrier_Univ
from django.views import View
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, JsonResponse
import json
from django.db.models import Q # new
from django.views.generic import ListView
from django.urls import reverse
import pdfkit
from django.http import HttpResponse
from django.template import loader
import io
from .utils import render_to_pdf
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .filters import CourrierFilter
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import DetailView







from django.forms import modelform_factory
# from .models import Picture

from django.core.files.storage import FileSystemStorage
# from .models import WebcamImage
from django.core.files.base import ContentFile
from django.utils import timezone
import re
from django.http import HttpResponseBadRequest




def chef_univ(request):

    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    form = RegistrationForm(request.POST or None)
    chef_univ = Courrier_Univ()

    if request.method == 'POST':

        if form.is_valid():

            chef_univ.transmetteur = form.cleaned_data['transmetteur']                
            chef_univ.recepteur = form.cleaned_data['recepteur']                
            chef_univ.code = form.cleaned_data['code']                
            chef_univ.date = form.cleaned_data['date']                
            chef_univ.objet = form.cleaned_data['objet']
            chef_univ.structure = form.cleaned_data['structure']                
            chef_univ.annee = form.cleaned_data['annee']
            chef_univ.types = form.cleaned_data['types']
        
            chef_univ.save()

            messages.add_message(request, messages.SUCCESS, (f"Informations du courrier enregistrées avec succès."))
            return redirect('univ:chef_univ')
        else:
            messages.add_message(request, messages.ERROR, ('Veuillez vérifier les champs en rouge !!!'))
            return render(request, 'univ/chef_univ.html', {'form': form})

    context = {
        'form': form,
        'count_courrier': count_courrier,
    }
    return render(request,'univ/chef_univ.html', context)



def bureau_univ(request):
    type_elt = request.GET.get('types')
    code = request.GET.get('code')
    courrier = Courrier_Univ.objects.filter(
        code=code, types=type_elt
    )
    sg = get_object_or_404(Courrier_Univ, code=code, types=type_elt)
    form = MentionForm(instance=sg)

    if request.method == 'POST':
        form = MentionForm(request.POST or None, instance=sg)
        if form.is_valid():
            sg.service_traitement = form.cleaned_data['service_traitement']
            sg.mention = form.cleaned_data['mention']                
            
            sg.save()
            messages.add_message(request, messages.SUCCESS, (f"Informations du courrier enregistrées avec succès."))

    return render(request,'univ/univ.html', {"courrier": courrier, "form": form})


def search_univ(request):

    if request.method == 'POST':
        query = request.POST.get('code')
        querys = request.POST.get('types')
        

        objects = Courrier_Univ.objects.filter(code=query, types=querys, structure="UNIVERSITE DE YAOUNDE 1")
        if not objects: 
            messages.error(request, "Le code ou le type fourni n'existe pas")
            return redirect('univ:search_univ')
        response = redirect('/univ/bureau_univ/' + f'?code={query}&types={querys}')
        return response
    else:
        return render(request, 'univ/search_univ.html')



def courrier_attente(request):
    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    # if request.method == 'POST':
    #     request.is_active = False
    #     request.save()
    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    return render(request, 'univ/courrier_attente.html', {"courrier": courrier,  "count_courrier": count_courrier})



def deactivate_record(request, id):
    record = get_object_or_404(Courrier_Univ, pk=id)
    if request.method == 'POST':
        record.is_active = False
        record.save()
        return HttpResponseRedirect('/')
    return render(request, 'univ/chef_univ.html', {"record": record})



def courrier_attente_detail(request, id):
    obj = get_object_or_404(Courrier_Univ, pk=id)

    #compter le nombre de courrier
    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    return render(request, 'univ/courrier_detail.html', {"obj": obj, "count_courrier": count_courrier})



# def traited(request):
#     is_active = False
#     request.object.save()
#     return redirect('senat:courrier_attente')



def search_chef(request):

    if request.method == 'POST':
        query = request.POST.get('code')
        querys = request.POST.get('types')
        queryss = request.POST.get('objet')


        response = redirect('/univ/result_chef/' + f'?code={query}&types={querys}&objet={queryss}' or f'?code={query}&types={querys}&objet={queryss}' or f'?objet={queryss}')
        return response
    else:
        return render(request, 'univ/search_chef.html')



def result_chef(request):
     #compter le nombre de courrier
    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    type_elt = request.GET.get('types')
    code = request.GET.get('code')
    objet = request.GET.get('objet')



    courrier = Courrier_Univ.objects.filter(
        code=code, types=type_elt
    ) or Courrier_Univ.objects.filter(
        code=code, types=type_elt, objet=objet
    )or Courrier_Univ.objects.filter(
        objet=objet
    )
    return render(request,'univ/result_chef.html', {"courrier": courrier, "count_courrier": count_courrier})



def courrier_pdf(request, pk):
    user_courrier = Courrier_Univ.objects.get(pk=pk)

    context = {
        "user_courrier": user_courrier,
    }
    
    pdf = render_to_pdf('univ/courrier_pdf.html', context)
    return HttpResponse(pdf, content_type='application/pdf')



def list_courrier(request):
    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    courriers = Courrier_Univ.objects.all()
    # courriers = Courrier.objects.filter(is_active=True).order_by('-created_on')

    #pagination
    # page = request.GET.get('page')
    # num_of_items = 3
    # paginator = Paginator(courriers, num_of_items)

    # try:
    #     courrierss = paginator.page(page)
    # except PageNotAnInteger:
    #     page = 1
    #     courrierss = paginator.page(page)
    # except EmptyPage:
    #     page = paginator.num_pages
    #     courrierss = paginator.page(page)

    #barre de filtre
    courriers_filter = CourrierFilter(request.GET, queryset=courriers)

    return render(request, 'univ/liste_courrier.html', {'courriers': courriers, 
                                                   'count_courrier': count_courrier, 
                                                #    'paginator': paginator,
                                                   'courriers_filter':courriers_filter,
                                                   })



def envoi_email(request):
    courrier = Courrier_Univ.objects.filter(mention="ETUDE ET COMPTE RENDU", is_active=True)
    count_courrier = courrier.count()

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        # phone = request.POST.get('phone')
        message = request.POST.get('message')
        attachment = request.FILES.get('attachment')
        form_data = {
            'name':name,
            'email':email,
            # 'phone':phone,
            'message':message,
            'attachment':MIMEMultipart(),
        }
        recipient_list = email
        # message = '''
        # From:\n\t\t{}\n
        # Message:\n\t\t{}\n
        # Email:\n\t\t{}\n
        
        
        
        # '''.format(form_data['name'], form_data['message'], form_data['email'])
        # send_mail('You got a mail!', message, '', ['ngounouloic853@gmail.com']) # TODO: enter your email address
        send_mail(name, message, email, [recipient_list], attachment)
        

    return render(request,'univ/envoi_email.html', {"courrier": courrier, "count_courrier": count_courrier})








import base64
import io
import numpy as np
import cv2
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import Capture
from io import BytesIO
from django.utils.encoding import smart_str
from reportlab.lib.pagesizes import letter
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas


def indexs(request):
    return render(request, 'indexs.html')



# def capture(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         image_data = request.POST.get('image')
#         image_data = image_data.replace('data:image/png;base64,', '')
#         image_data = base64.b64decode(image_data)
#         capture = Capture(name=name)
#         image_file = BytesIO(image_data)
#         capture.image.save(name + '.png', image_file)
#         capture.save()
#         return redirect('senat:captures')
#     return render(request, 'capture.html')

univ/templates/univ/courrier_detail.html
{% load static %}
{% load crispy_forms_tags %}





<!DOCTYPE html>
<html>
<head>
  <title> Enregistrement du courrier - Chef service du courrier </title>
<meta charset="UTF-8">
<!-- This script got from frontendfreecode.com -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<link rel="icon" type="image/x-icon" href="{% static 'landing/assets/img/favicon.png' %}">


<style>
    @import url('https://fonts.googleapis.com/css?family=Muli&display=swap');
    @import url('https://fonts.googleapis.com/css?family=Quicksand&display=swap');
body {
    font-family: 'Quicksand', sans-serif;
    /*font-size: 14px;
    line-height: 1.8;
    font-weight: normal;
    background: #fafafa;*/
  
}
.wrapper {
    display: flex;
    width: 100%;
}

.img {
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
}

#sidebar {
    height: 100%;
    width: 300px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #6A4E77; 
    overflow-x: hidden;
    transition: all 0.3s;
}

#sidebar .sidebar-header {
    padding: 20px;
    /*background-color: #6A4E77;*/
    color: #fff;
}

#sidebar ul.components {
    padding: 20px 0;
    /*border-bottom: 1px solid #47748b;*/
}

#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    padding-left: 20px;
    font-size: 1.1em;
    display: block;
    color: #fff;
    text-decoration: none;
}

#sidebar ul li a:hover {
    text-decoration: none;
    background-color:  #ae17aa;
}

#sidebarCollapse {
    display: none;
}

#content {
    width: 100%;
    padding-left: 350px;
    transition: all 0.3s;
}

.head{
    margin-top: 50px;
}
.head1{
    text-align: center;
    line-height: 10px;
}
.head2{
    width: 550px;
}
.head3{
    text-align: center;
    line-height: 10px;
}
.objet{
    text-align: center;
}
.objet h6{
    text-decoration: underline;
}
.objet1{
    width: 300px;
}
.objet2{
    width: 300px;
}



/*--------------------------------------------------------------
# Sections General
--------------------------------------------------------------*/
.section-title {
    margin-top: 30px;
    text-align: center;
    padding: 30px 0;
    position: relative;
  }
  
  .section-title h2 {
    font-size: 32px;
    font-weight: 700;
    text-transform: uppercase;
    margin-bottom: 20px;
    padding-bottom: 0;
    color: #191919;
    position: relative;
    z-index: 2;
  }
  
  .section-title span {
    position: absolute;
    top: 30px;
    color: #f4f4f4;
    left: 0;
    right: 0;
    z-index: 1;
    font-weight: 700;
    font-size: 52px;
    text-transform: uppercase;
    line-height: 0;
  }
  
  .section-title p {
    margin-bottom: 0;
    position: relative;
    z-index: 2;
  }
  
  @media (max-width: 575px) {
    .section-title h2 {
      font-size: 28px;
      margin-bottom: 15px;
    }
  
    .section-title span {
      font-size: 38px;
    }
  }
</style>

</head>
<body>


    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header text-center">
                {% comment %} <h5>Cybex Courrier</h5> {% endcomment %}
                <img src="{% static 'landing/assets/img/cybex-logo.png' %}" class="" style="width: 250px;">
            </div>
            {% comment %} <a href="#" class="img logo rounded-circle mb-3" style="background-image: url(http://frontendfreecode.com/img/user.jpg);"></a> {% endcomment %}
            <div class="text-center">
                <img src="{% static 'landing/assets/img/about.jpg' %}" class="img logo rounded-circle mb-3 mt-2" style="width: 100px; height: 100px;">
            </div>
            <p class="text-center" style="color: #fff"><span style="font-size: 20px; color: #fff">{{ user.username | upper }}</span> <br> Chef Université</p>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="{% url 'account:index' %}">
                        <i class="ri-logout-circle-line"></i>
                        Deconnexion
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:chef_univ' %}">
                        <i class="fas fa-user mr-2"></i>
                        Enregistrer un Courrier
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:courrier_attente' %}">
                        <i class="fas fa-user mr-2"></i>
                        Courrier en attente <span style="font-size:10px; border: 1px solid red; padding-left: 3px; padding-right: 3px; border-radius: %; background-color: red">{{ count_courrier }}</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:search_chef' %}">
                        <i class="fas fa-tasks mr-2"></i>
                        Recherche d'un Courrier
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:list_courrier' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Listing des Courriers
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:envoi_email' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Email
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:scan' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Scanner un Courrier
                    </a>
                </li>
                <li>
                    <a href="{% url 'univ:captures' %}">
                        <i class="fas fa-cog mr-2"></i>
                        Imprimer un Courrier
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Page Content -->
        <div id="content" >
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                </div>
            </nav>
            <div class="container-fluid">
                {% comment %} <h2 class="mb-4 mt-4">DETAIL DU COURRIER</h2> {% endcomment %}
                <div class="section-title">
                    <span>DETAIL DU COURRIER</span>
                    <h2>DETAIL DU COURRIER</h2>
                </div>
                <div class="container">
                    <table class="head">
                        <tr>
                            <td class="head1">
                                <p>REPUBLIQUE DU CAMEROUN</p>
                                <p>Paix-Travail-Patrie</p>
                                <p>--------</p>
                                <p>UNIVERSITE DE YAOUNDE 1</p>
                                <p>--------</p>
                            </td>
                            <td class="head2">
            
                            </td>
                            <td class="head3">
                                <p>REPUBLIC OF CAMEROON</p>
                                <p>Peace-Work-Fatherland</p>
                                <p>--------</p>
                                <p>UNIVERSITY OF YAOUNDE 1</p>
                                <p>--------</p>
                            </td>
                        </tr>
                    </table>
                    <br><br><br>
                    <table class="obj">
                        <tr>
                            <td class="objet1">
                                
                            </td>
                            <td class="objet">
                                <h6>{{ obj.types }} / {{ obj.code }} / UY1 DU {{ obj.date }}</h6><br>
                                <p>{{ obj.objet }}.
                                </p>
                            </td>
                            <td class="objet2">
                                
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

















{% comment %} <div class="wrapper d-flex align-items-stretch">
    <nav id="sidebar">
        <div class="p-4 pt-5">
            <a href="#" class="img logo rounded-circle mb-3" style="background-image: url(http://frontendfreecode.com/img/user.jpg);"></a>
            
            <p class="text-center"><span style="font-size: 20px">{{ user.username | upper }}</span> <br> Chef du Service Courrier</p>
            <ul class="list-unstyled components mb-5 mt-5">
                <li>
                    <a href="{% url 'account:index' %}">Deconnexion</a>
                </li>
                <li>
                    <a href="{% url 'senat:chef_service' %}">Enregistrer un Courrier</a>
                </li>
                <li>
                    <a href="{% url 'senat:courrier_attente' %}">Courrier en attente <span style="font-size:10px; border: 1px solid red; padding-left: 3px; padding-right: 3px; border-radius: %; background-color: red">{{ count_courrier }}</span></a>
                </li>
                <li>
                    <a href="{% url 'senat:search_chef' %}">Recherche d'un Courrier </a>
                </li>
                <li>
                    <a href="{% url 'senat:list_courrier' %}">Imprimer un Courrier </a>
                </li>
            </ul>
            
        </div>
    </nav>
    <div id="content" class="p-4 p-md-5 ">
            <div class="container-fluid">
            </div>
        <h2 class="mb-4 mt-4">DETAIL DU COURRIER</h2>

        
            <div class="container">
                    <table class="head">
                        <tr>
                            <td class="head1">
                                <p>REPUBLIQUE DU CAMEROUN</p>
                                <p>Paix-Travail-Patrie</p>
                                <p>--------</p>
                                <p>SENAT</p>
                                <p>--------</p>
                            </td>
                            <td class="head2">
            
                            </td>
                            <td class="head3">
                                <p>REPUBLIC OF CAMEROON</p>
                                <p>Peace-Work-Fatherland</p>
                                <p>--------</p>
                                <p>SENATE</p>
                                <p>--------</p>
                            </td>
                        </tr>
                    </table>
                    <br><br><br>
                    <table class="obj">
                        <tr>
                            <td class="objet1">
                                
                            </td>
                            <td class="objet">
                                <h6>{{ obj.types }} N 23 / {{ obj.code }} / AB / SEN DU {{ obj.date }}</h6><br>
                                <p>{{ obj.objet }}.
                                </p>
                            </td>
                            <td class="objet2">
                                
                            </td>
                        </tr>
                    </table>
                
            </div>
     


    </div> {% endcomment %}
    {% comment %} <div class="" style="margin-top: 15em;">
        <div class="card text-white" style="margin-right:3rem; border-color: #2a5555">
            <div class="card-header" style="background-color: #2a5555; font-weight: bold; font-size: 20px">NOTICE</div>
            <div class="card-body">
                <p class="card-text"style="color: #111; font-size: 15px">Une fois sur cette page vous avez la possibilité de vous <b>déconnecter</b>, <b>d'enregistrer un courrier</b> en 
                    renseignant <b>le transmetteur, le recepteur, le code, la date, l'objet du courrier</b> qui sont tous des champs <b>obligatoires</b> et en cliquant
                    sur <b>enregistrer</b>, vous allez recevoir un message de succès dans le cas ou les champs sont bien remplis et votre mission est terminé.
                </p>
            </div>
        </div>
    </div> {% endcomment %}
{% comment %} </div>
<script>
(function ($) {
    "use strict";
    var fullHeight = function () {
        $(".js-fullheight").css("height", $(window).height());
        $(window).resize(function () {
            $(".js-fullheight").css("height", $(window).height());
        });
    };
    fullHeight();
    $("#sidebarCollapse").on("click", function () {
        $("#sidebar").toggleClass("active");
    });
})(jQuery);
</script> {% endcomment %}

</body>
</html>

univ/templates/univ/courrier_pdf.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title> Enregistrement du courrier - Chef service du courrier </title>
        <meta charset="UTF-8">
        <!-- This script got from frontendfreecode.com -->

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="icon" type="image/x-icon" href="{% static 'landing/assets/img/favicon.png' %}">


        <style>
            .head{
                margin-top: 150px;
            }
            .head1{
                text-align: center;
                line-height: 10px;
            }
            .head2{
                width: 300px;
            }
            .head3{
                text-align: center;
                line-height: 10px;
            }
            .objet{
                text-align: center;
            }
            .objet h6{
                text-decoration: underline;
            }
            .objet1{
                width: 100px;
            }
            .objet2{
                width: 100px;
            }
        </style>

    </head>
    <body>
        <div class= "container">
            <table class="head">
                <tr>
                    <td class="head1">
                        <p>REPUBLIQUE DU CAMEROUN</p>
                        <p>Paix-Travail-Patrie</p>
                        <p>--------</p>
                        <p>SENAT</p>
                        <p>--------</p>
                    </td>
                    <td class="head2">
    
                    </td>
                    <td class="head3">
                        <p>REPUBLIC OF CAMEROON</p>
                        <p>Peace-Work-Fatherland</p>
                        <p>--------</p>
                        <p>SENATE</p>
                        <p>--------</p>
                    </td>
                </tr>
            </table>
            <br><br><br>
            <table class="obj">
                <tr>
                    <td class="objet1">
                        
                    </td>
                    <td class="objet">
                        <h6>{{ user_courrier.types }} N° 23 / {{ user_courrier.code }} / AB / SEN {% if user_courrier.date %} DU {{ user_courrier.date }} {% else %} DE {{ user_courrier.annee }} {% endif %}</h6><br>
                        <p>{{ user_courrier.objet }}.
                        </p>
                    </td>
                    <td class="objet2">
                        
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>

univ/templates/univ/indexs.html
{% block content %}
    <h1>Webcam Capture</h1>
    <p><a href="{% url 'senat:capture' %}">Capture</a></p>
    <p><a href="{% url 'senat:captures' %}">Captures</a></p>
{% endblock %}