accounts/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path('index/', views.index, name='index'),
    path('login/', views.user_login, name='user_login'),
    path('register/', views.register, name='register'),
    # path('chef_service/', views.chef_service, name='chef_service'),
    # path('chef_depart/', views.chef_depart, name='chef_depart'),
    # path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path('sg/', views.sg, name='sg'),
    # path('usager/', views.usager, name='usager'),
]

courrier/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('senat.urls')),
    path('univ/', include('univ.urls')),
    path("", index),
]
if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

univ/urls.py
from django.urls import path
from . import views
from .views import *
# from .views import SearchResultsView
# from .views import SearchResultsList

app_name = "univ"

urlpatterns = [
    path('chef_univ/', views.chef_univ, name='chef_univ'),
    # path('chef_depart/', views.chef_depart, name='chef_depart'),
    # path('chef_arrive/', views.chef_arrive, name='chef_arrive'),
    # path(r'^(?P<id>\d+)bureau_sg/$', views.bureau_sg, name='bureau_sg'),
    # path('bureau_sg/', views.bureau_sg, name='bureau_sg'),
    path('bureau_univ/', views.bureau_univ, name='bureau_univ'),
    # path('usager/', views.usager, name='usager'),
    # path('search/', views.search, name='search'),
    path('search_univ/', views.search_univ, name='search_univ'),
    path('courrier_attente/', views.courrier_attente, name='courrier_attente'),

    

    path('<int:id>', views.courrier_attente_detail, name='courrier_attente_detail'),
    path('search_chef/', views.search_chef, name='search_chef'),
    path('result_chef/', views.result_chef, name='result_chef'),
    path('/', views.list_courrier, name='list_courrier'),
    path('df/<int:pk>/', views.courrier_pdf, name="courrier_pdf"),
    # path('traited/', views.traited, name='traited'),
    # path("search/", SearchResultsList.as_view(), name="search"),
    # path("search/", SearchResultsView.as_view(), name="search_results"),
    # path('sg_record/', sg_record, name='sg_record'),
    path('envoi_email/', views.envoi_email, name='envoi_email'),

    path('scan', views.scan, name='scan'),




    path('<int:id>', views.deactivate_record, name='deactivate_record'),






    # path('inde/', views.indexs, name='indexs'),
    # path('capture/', views.capture, name='capture'),
    path('captures/', views.captures, name='captures'),
    path('capture/<int:capture_id>/download/', views.download_capture, name='download_capture'),
    path('capture_pdf/<int:capture_id>/download/', views.download_capture_pdf, name='download_capture_pdf'),




    path('search_usager/', views.search_usager, name='search_usager'),
    path('result_usager/', views.result_usager, name='result_usager'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    is_Chef_service= models.BooleanField('Is Chef Service', default=False)
    is_Chef_univ= models.BooleanField('Is Chef Universite', default=False)
    is_Chef_bureau_depart= models.BooleanField('Is Chef bureau depart', default=False)
    is_Chef_bureau_arrive= models.BooleanField('Is Chef bureau arrive', default=False)
    is_Secretaire_general= models.BooleanField('Is Secretaire general', default=False)
    is_Universite= models.BooleanField('is_Universite', default=False)
    is_Usager = models.BooleanField('Is Usager', default=False)
    phone = models.CharField(max_length=9)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'username', 
            'email', 
            'password1', 
            'password2', 
            'is_Chef_service', 
            'is_Chef_univ', 
            'is_Chef_bureau_depart', 
            'is_Chef_bureau_arrive',
            'is_Secretaire_general',
            'is_Universite',
            'is_Usager'
            )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, LoginForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .models import User
from tablib import Dataset



def index(request):
    return render(request,'index.html')








def register(request):
    msg = None
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            msg = 'user created'
            return redirect('login_view')
        else:
            msg = 'form is not valid'
    else:
        form = SignUpForm()
    return render(request,'register.html', {'form': form, 'msg': msg})




def user_login(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            userSch = User.objects.get(email=email)
            print(userSch)
        except:
            userSch = None

        print(userSch)

        if userSch == None:
            messages.error(request, 'Utilisateur non trouvé !')
            return render(request, 'login.html')
        else:
            username = userSch.username
            user = authenticate(
                request, username=username, password=password)
        if user is not None and user.is_Chef_service:
            login(request, user)
            return redirect('senat:chef_service')
        elif user is not None and user.is_Chef_univ:
            login(request, user)
            return redirect('univ:chef_univ')
        elif user is not None and user.is_Chef_bureau_depart:
            login(request, user)
            return redirect('senat:chef_depart')
        elif user is not None and user.is_Chef_bureau_arrive:
            login(request, user)
            return redirect('senat:chef_arrive')
        elif user is not None and user.is_Secretaire_general:
            login(request, user)
            return redirect('senat:search')
        elif user is not None and user.is_Universite:
            login(request, user)
            return redirect('univ:search_univ')
        elif user is not None and user.is_Usager:
            login(request, user)
            return redirect('senat:usager')
        else:
            messages.error(request, 'Incorrect Email OR password')

    context = {}
    return render(request, 'login.html', context)

accounts/templates/login.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Connexion pour la gestion du courrier au Sénat</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'landing/assets/css/style1.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'landing/assets/img/favicon.png' %}">
    <style>
        .login-dark form{  
            background-color:  rgba(0, 0, 0, 0.9);
        }
    </style>
</head>

{% comment %} <body style="background: #214a80;"> {% endcomment %}
<body>
    
    <div class="login-dark" style="height: 695px; margin-top: -80px; ">
        <form action="{% url 'account:user_login' %}" method="POST">
            <div class="text-center">
                <a href="{% url 'account:index' %}">
                    {% comment %} <img src="{% static 'landing/assets/img/sceau.png' %}" style="width: 80px; padding-bottom:50px; margin-left: 30%"> {% endcomment %}
                    <img src="{% static 'landing/assets/img/cybex-logo.png' %}" style="width: 200px; margin-bottom:80px; ">
                </a>
            </div>
            {% csrf_token %}
            {% comment %} <h2 class="sr-only">Login Form</h2>
            <div class="illustration">
                <i class="icon ion-ios-locked-outline"></i>
            </div> {% endcomment %}
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Email" required data-error="NEW ERROR MESSAGE">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password" required data-error="NEW ERROR MESSAGE">
            </div>
            <div class="form-group">
                <button class="btn btn-primary btn-block" style="background-color: #2a5555; outline: none">Log In</button>
            </div>
            <a class="forgot" href="#">Forgot your email or password?</a>
        </form>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
</body>

</html>